name: Build Godot Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux-X11, windows-x64, windows-x86, WebGL]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@master
        with:
          name: MAgicalMunchies
          preset: ${{ matrix.platform }}
          debugMode: "true"
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Client - ${{ matrix.platform }}
      #     path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
